# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestBS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Starscream'
  pod 'SwiftyJSON'

  target 'TestBSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestBSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
